language: node_js
node_js:
  - node
script: yarn build
deploy:
  edge: true
  provider: npm
  email: nw55@outlook.com
  api_token:
    secure: H59NfRmacsandJAoxDufGtsy34BkyN8li6Fh9sTjJZLB0uNLBBoTmOZaofzadqQLkEvXNYLm4l82xzNJ24DGj0rokQ6TrhA/2qI1tLushQM26U3FCUC8KXqoBk3qO2Z8hmenMg4gM0wRFi9lmZU/t5QwjW1EYQ7oO+3Qc5YYcZDVpf4+/U9nAYLFGqKagaJjPo6ky4Qz14MwK11W7Hx4v4V9lJQ5h7uvpQ7dKoFe9Nh2V6qdXc0C2TfEKJplpS7wRYSiR8aMGwhBJ+jX5MboUjqslYNr8m+ETyF4h40zayKTOIy04SDMnqX2p6jUqegCNgeYFCKe6YlASbBOF0J0TA+vmbhD2f85KPsXguJAzgpA6ooisYBm4FKlhpDeM/SykC1pTVR46p97JJiUdlC7ede4YuahXCU3AS/MiL38TkbuBGn/UriIwn7FN4eoIo9pjb3Kzi3Xyes/QZJMnLHFkKihMRKzpmoKDPzcxK2j4iYRFdTbz1BDnUQPSTt/l0GPm/97kddq0MtpAl9Etn3VXGLNG+/HspuYI07/fbAXwiTqyhtSZ+w0WNBioj7Ef9QVBUzdvnK/2o5EA4MV8v0eo68+7CX5hG+2FrjXzhXRnVFm866vE3T95FGC6TQWpAChe3cM16EbKlp7UHijXYU6bLSLikNWhxmMCaHbMw6BiA0=
  on:
    tags: true
    branch: master
